import * as fs from "node:fs";
import * as path from "node:path";
import { glob } from "glob";
import gradient from "gradient-string";
import inquirer from "inquirer";
import ora from "ora";
import pc from "picocolors";
import { loadUserConfig, mergeConfigs } from "magic-helix-core";
import type {
	ConfigFileTagMap,
	DependencyTagMap,
	FileGlobTagMap,
	TagTemplateMap,
} from "magic-helix-core";

// --- CONFIGURATION ---
const ROOT_PACKAGE_JSON = path.resolve(process.cwd(), "package.json");
const BUILT_IN_TEMPLATE_DIR = path.resolve(
	__dirname,
	"..",
	"default_templates",
);

// --- TYPES ---
interface Project {
	name: string; // Sanitized package name, e.g., 'scope-my-app'
	path: string; // Relative path from root, e.g., 'packages/my-app'
	tags: Set<string>;
}

/**
 * The 'run' command.
 * Scans the monorepo and generates instruction files.
 */
export async function run() {
	console.log(gradient.pastel.multiline("🤖 Running AI Convention Aligner..."));

	const mainSpinner = ora("Loading configurations...").start();

	// 1. Load Configs (Built-in + Optional User)
	const userConfig = loadUserConfig();
	const config = mergeConfigs(userConfig);
	mainSpinner.succeed("Configuration loaded.");

	const { dependencyTagMap, configFileTagMap, fileGlobTagMap, tagTemplateMap } =
		config;

	const userTemplateDir = path.resolve(
		process.cwd(),
		config.templateDirectory as string,
	);
	const targetDir = path.resolve(
		process.cwd(),
		config.outputDirectory as string,
	);

	// 2. Find all projects
	const projectSpinner = ora("Scanning for projects...").start();
	const projects = await findProjects();
	if (projects.length === 0) {
		projectSpinner.warn(
			pc.yellow(
				'No projects found. Make sure your root package.json has a "workspaces" field.',
			),
		);
		return;
	}
	projectSpinner.succeed(`Found ${projects.length} projects.`);

	// 3. Analyze dependencies and tag projects
	const analyzeSpinner = ora("Analyzing project tags...").start();
	let totalTags = 0;
	for (const project of projects) {
		await analyzeProject(
			project,
			dependencyTagMap as DependencyTagMap,
			configFileTagMap as ConfigFileTagMap,
			fileGlobTagMap as FileGlobTagMap,
		);
		totalTags += project.tags.size;
	}
	analyzeSpinner.succeed(`Project analysis complete. Found ${totalTags} tags.`);

	// 4. Ensure target directory exists
	ensureTargetDir(targetDir);

	// 5. Generate files
	console.log(
		pc.cyan(`\nGenerating instruction files in ${config.outputDirectory}...`),
	);
	const generatedFiles: string[] = [];
	for (const project of projects) {
		if (project.tags.size === 0) {
			console.log(pc.gray(`  Skipping: ${project.name} (No matching tags)`));
			continue;
		}

		console.log(pc.bold(`  Processing: ${project.name}`));
		console.log(pc.gray(`    Tags: ${[...project.tags].join(", ")}`));

		const globPattern = `${project.path}/src/**/*.{ts,js,vue,tsx,jsx,go,py}`;

		for (const tag of project.tags) {
			const templates = (tagTemplateMap as TagTemplateMap)[tag];
			if (!templates) continue;

			for (const t of templates) {
				// Check for template in user's dir *first*, then fall back to built-in
				let templateContent = readTemplate(userTemplateDir, t.template);
				let source = "Custom";

				if (!templateContent) {
					templateContent = readTemplate(BUILT_IN_TEMPLATE_DIR, t.template);
					source = "Built-in";
				}

				if (!templateContent) {
					console.warn(pc.yellow(`    ⚠️  Template not found: ${t.template}`));
					continue;
				}

				const header = `---
# Auto-generated by ai-aligner for: ${project.name}
# Source Template: ${t.template}
applyTo: "${globPattern}"
---
`;
				const fullContent = `${header}\n${templateContent}`;

				const outputFilename = `${project.name}.${t.suffix}`;
				const outputPath = path.join(targetDir, outputFilename);

				generatedFiles.push(outputFilename);
				fs.writeFileSync(outputPath, fullContent);
				console.log(
					pc.green(
						`    ✅ Generated: ${pc.bold(outputFilename)} (from ${source})`,
					),
				);
			}
		}
	}

	// 6. Pruning: Ask to remove old files
	await pruneOldFiles(targetDir, generatedFiles);

	console.log("\n✨ Alignment complete!");
	console.log(`Generated files are in: ${config.outputDirectory}`);

	if (config.target === "github-copilot") {
		console.log("\n--- VS Code + GitHub Copilot Tip ---");
		console.log(
			"To maximize Copilot's awareness, add this to your workspace .vscode/settings.json:",
		);
		console.log(`
  "github.copilot.advanced": {
    "instructions": ".github/instructions"
  }
    `);
		console.log(
			"This tells Copilot to *always* read these files. Restart VS Code after adding.",
		);
	}
}

// --- HELPER FUNCTIONS ---

function ensureTargetDir(targetDir: string) {
	const spinner = ora(`Checking target directory: ${targetDir}`).start();
	if (!fs.existsSync(targetDir)) {
		spinner.text = "Target directory not found. Creating...";
		try {
			fs.mkdirSync(targetDir, { recursive: true });
			spinner.succeed(`Created ${targetDir}`);
		} catch (error) {
			spinner.fail(
				pc.red(
					`Error creating directory: ${(error as Error).message}. Please check permissions.`,
				),
			);
			process.exit(1);
		}
	} else {
		spinner.succeed("Target directory OK.");
	}
}

async function findProjects(): Promise<Project[]> {
	const projects: Project[] = [];

	if (!fs.existsSync(ROOT_PACKAGE_JSON)) {
		throw new Error("No root package.json found. Cannot find projects.");
	}

	const rootPkg = JSON.parse(fs.readFileSync(ROOT_PACKAGE_JSON, "utf-8"));
	const workspaces = rootPkg.workspaces?.packages || rootPkg.workspaces || [];

	// 1. Add root project
	projects.push({
		name: rootPkg.name
			? rootPkg.name.replace(/@/g, "").replace(/\//g, "-")
			: "root-project",
		path: ".",
		tags: new Set<string>(),
	});

	if (workspaces.length === 0) {
		console.log("No workspaces found. Analyzing root project only.");
		return projects;
	}

	// 2. Add workspace projects
	const packageJsonPaths = await glob(
		workspaces.map((w: string) => `${w}/package.json`),
	);

	for (const pkgPath of packageJsonPaths) {
		try {
			const pkgContent = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
			projects.push({
				name: pkgContent.name.replace(/@/g, "").replace(/\//g, "-"), // e.g., @scope/my-app -> scope-my-app
				path: path.dirname(pkgPath),
				tags: new Set<string>(),
			});
		} catch (_e) {
			console.warn(pc.yellow(`⚠️  Skipping invalid package.json: ${pkgPath}`));
		}
	}

	return projects;
}

async function analyzeProject(
	project: Project,
	depMap: DependencyTagMap,
	configMap: ConfigFileTagMap,
	globMap: FileGlobTagMap,
) {
	const projectRoot = path.resolve(process.cwd(), project.path);

	// Strategy 1: Analyze package.json dependencies
	try {
		const pkgPath = path.join(projectRoot, "package.json");
		if (fs.existsSync(pkgPath)) {
			const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
			const allDeps = {
				...(pkg.dependencies || {}),
				...(pkg.devDependencies || {}),
			};

			for (const dep in allDeps) {
				if (depMap[dep]) {
					project.tags.add(depMap[dep]);
				}
			}
		}
	} catch (e) {
		console.warn(
			pc.yellow(
				`⚠️  Could not parse package.json for ${project.name}: ${(e as Error).message}`,
			),
		);
	}

	// Strategy 2: Analyze key config files
	try {
		for (const file in configMap) {
			const tag = configMap[file];
			const configPath = path.join(projectRoot, file);
			if (fs.existsSync(configPath)) {
				project.tags.add(tag);
			}
		}
	} catch (e) {
		console.warn(
			pc.yellow(
				`⚠️  Error scanning config files for ${project.name}: ${(e as Error).message}`,
			),
		);
	}

	// Strategy 3: Analyze file globs
	try {
		for (const pattern in globMap) {
			const tag = globMap[pattern];
			// Use 'glob' package for async globbing
			const results = await glob(pattern, {
				cwd: projectRoot,
				nodir: true,
				dot: true, // Include dotfiles if needed, though 'src' patterns usually don't
			});
			if (results.length > 0) {
				project.tags.add(tag);
			}
		}
	} catch (e) {
		console.warn(
			pc.yellow(
				`⚠️  Error scanning file globs for ${project.name}: ${(e as Error).message}`,
			),
		);
	}
}

function readTemplate(dir: string, templateFile: string): string | null {
	const p = path.join(dir, templateFile);
	try {
		return fs.readFileSync(p, "utf-8");
	} catch (_e) {
		return null; // Will be handled in the main function
	}
}

async function pruneOldFiles(targetDir: string, generatedFiles: string[]) {
	const existingFiles = fs
		.readdirSync(targetDir)
		.filter((f) => f.endsWith(".md"));

	const oldFiles = existingFiles.filter((f) => !generatedFiles.includes(f));

	if (oldFiles.length > 0) {
		console.warn(
			pc.yellow(
				`\n⚠️  Found ${oldFiles.length} instruction files that are no longer generated:`,
			),
		);
		for (const f of oldFiles) {
			console.warn(pc.yellow(`  - ${f}`));
		}

		const { prune } = await inquirer.prompt([
			{
				type: "confirm",
				name: "prune",
				message: `Do you want to delete these ${oldFiles.length} old files?`,
				default: false,
			},
		]);

		if (prune) {
			let deleteCount = 0;
			for (const file of oldFiles) {
				try {
					fs.unlinkSync(path.join(targetDir, file));
					deleteCount++;
				} catch (e) {
					console.error(
						pc.red(`  ❌ Error deleting ${file}: ${(e as Error).message}`),
					);
				}
			}
			console.log(`✅ Pruned ${deleteCount} old files.`);
		}
	}
}
