/**
 * Mock data for the web playground
 * In a real application, these would be loaded from the core package or API
 */

export const mockTemplates: Record<string, string> = {
	"vue/vue-core.md": `# Vue Core Rules
- Use Composition API.
- Use <script setup>.
---`,
	"vue/vue-pinia.md": `# Pinia Rules
- Use setup stores.
---`,
	"vue/style-primevue.md": `# PrimeVue Rules
- Use PassThrough (PT) for styling.
---`,
	"react/react-core.md": `# React Core Rules
- Use Functional Components and Hooks.
---`,
	"react/react-zustand.md": `# Zustand Rules
- Define actions in the store.
---`,
	"nestjs/nestjs-core.md": `# NestJS Rules
- Use Module > Controller > Service.
---`,
	"generic/style-tailwind.md": `# Tailwind Rules
- Use utility classes.
---`,
	"generic/test-vitest.md": `# Vitest Rules
- Use \`vi.mock()\` for dependencies.
---`,
	"generic/lang-typescript.md": `# TypeScript Rules
- Avoid \`any\`.
---`,
	"generic/state-rxjs.md": `# RxJS Rules
- Suffix observables with \`$\`.
---`,
};

/**
 * Generate file header for instruction files
 */
export function generateFileHeader(
	projectName: string,
	templateName: string,
): string {
	return `---
# Auto-generated by magic-helix for: ${projectName}
# Source Template: ${templateName}
applyTo: "approximated/path/src/**/*"
---
`;
}
